# -*- coding: utf-8 -*-
"""EBAC - Tarefa 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flnlIezc5j5YupvLgwFYQDq8zwGY1s93
"""

nome = input ('Qual seu nome? ') #Nome da Pessoa
acao = input ('Escolha uma operação matemática (+, -, *, /): ') #Operação Matématica
num1 = int (input ('Insira o primeiro número:')) #Primeiro Número Covertido
num2 = int (input ('Insira o segundo número:')) #Segundo Número Convertido

if acao == '+': #Ação Soma
  resultado = num1 + num2
  print ('Olá,', nome, '. O resultado da sua soma é:', resultado)
elif acao == '-': #Ação Subtração
  resultado = num1 - num2
  print ('Olá,', nome,'. O resultado da sua subtração é:', resultado)
elif acao == '*': #Ação Multiplicação
  resultado = num1 * num2
  print ('Olá,' , nome,'. O resultado da sua multiplicação é:', resultado)
elif acao == '/': #Ação Divisão
  resultado = num1 / num2
  print ('Olá,', nome,'. O resultado da sua divisão é:', resultado)
else:
  print ('Essa operação é inválida. Tente de novo')